print("Welcome to python programming") 
print ("Please enter your name :") 
name=input() 
print ("Hello Mr/Ms.",(name), "Welcome") 
print("Please enter your age :") 
age=input() 
print ('Your age will be '+str(int(age)+1) +' in a year!!!') 
print ("The length of your name is :") 
print (len(name))
